-- AlterTable
ALTER TABLE "Channel" ADD COLUMN     "botScore" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "chatsCreated" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "embeddedTranscripts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "isFineTuned" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "maxTokens" INTEGER NOT NULL DEFAULT 200,
ADD COLUMN     "model" TEXT NOT NULL DEFAULT 'gpt-3.5-turbo',
ADD COLUMN     "totalVideos" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "ChannelCredit" ADD COLUMN     "maxCredits" INTEGER NOT NULL DEFAULT 100000;
