-- AlterTable
ALTER TABLE "Channel" ADD COLUMN     "activationFunding" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "activationGoal" DOUBLE PRECISION NOT NULL DEFAULT 10;

-- AlterTable
ALTER TABLE "ChannelBoost" ALTER COLUMN "value" SET DATA TYPE DOUBLE PRECISION;
